# Generated by Django 6.0.7 on 2026-08-05 16:03

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from core.migrations.loaders.initial_data import importar_escolas, popular_estados_cidades


class Migration(migrations.Migration):

    atomic = False
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ibge', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='código IBGE')),
                ('nome_cidade', models.CharField(max_length=150, verbose_name='nome da cidade')),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
                'ordering': ('nome_cidade',),
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=100, unique=True, verbose_name='nome do estado')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='sigla')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'ordering': ('nome_estado',),
            },
        ),
        migrations.CreateModel(
            name='Educador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=150, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, validators=[core.validators.validate_birth_date], verbose_name='data de nascimento')),
                ('genero', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('NB', 'Não binário'), ('O', 'Outro'), ('NI', 'Prefiro não informar')], max_length=2, verbose_name='gênero')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9()\\s.-]{8,20}$', 'Informe um telefone válido.')], verbose_name='telefone')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('UNIAO_ESTAVEL', 'União estável'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='estado civil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educador', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'educador',
                'verbose_name_plural': 'educadores',
                'db_table': 'core_educador',
                'ordering': ('nome_completo', 'usuario__username'),
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id_escola', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID da escola')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='nome')),
                ('id_municipio', models.BigIntegerField(db_index=True, verbose_name='ID do município')),
                ('sigla_uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('restricao_atendimento', models.CharField(blank=True, max_length=100, verbose_name='restrição de atendimento')),
                ('localizacao', models.CharField(blank=True, max_length=50, verbose_name='localização')),
                ('localidade_diferenciada', models.CharField(blank=True, max_length=100, verbose_name='localidade diferenciada')),
                ('categoria_administrativa', models.CharField(blank=True, max_length=50, verbose_name='categoria administrativa')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='telefone')),
                ('dependencia_administrativa', models.CharField(blank=True, max_length=50, verbose_name='dependência administrativa')),
                ('categoria_privada', models.CharField(blank=True, max_length=100, verbose_name='categoria privada')),
                ('etapas_modalidades_oferecidas', models.TextField(blank=True, verbose_name='etapas e modalidades oferecidas')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['sigla_uf', 'id_municipio'], name='escola_uf_municipio_idx')],
            },
        ),
        migrations.CreateModel(
            name='EducadorEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_caracterizacao_turmas', models.CharField(choices=[('alfabetizacao_eja', 'Alfabetização EJA'), ('anos_iniciais_eja', 'Anos Iniciais EJA'), ('anos_finais_eja', 'Anos Finais EJA'), ('ensino_medio', 'Ensino Médio'), ('educacao_especial', 'Educação Especial'), ('educacao_profissional', 'Educação Profissional')], max_length=30, verbose_name='função e caracterização das turmas da EJA')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_educador_escola', to='core.cidade', verbose_name='cidade de atuação')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos_educador_escola', to='core.escola', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'vínculo entre educador e escola',
                'verbose_name_plural': 'vínculos entre educadores e escolas',
                'db_table': 'core_educadorescola',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='core.estado', verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='FuncaoEducador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcoes', to='core.educador', verbose_name='educador')),
                ('educador_escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcao_educador', to='core.educadorescola', verbose_name='atuação do educador na escola')),
            ],
            options={
                'verbose_name': 'função do educador',
                'verbose_name_plural': 'funções dos educadores',
                'db_table': 'core_funcaoeducador',
                'ordering': ('educador', 'educador_escola'),
            },
        ),
        migrations.AddIndex(
            model_name='cidade',
            index=models.Index(fields=['estado', 'nome_cidade'], name='cidade_estado_nome_idx'),
        ),
        migrations.AddConstraint(
            model_name='cidade',
            constraint=models.UniqueConstraint(fields=('estado', 'nome_cidade'), name='cidade_estado_nome_uniq'),
        ),
        migrations.RunPython(popular_estados_cidades, migrations.RunPython.noop),
        migrations.RunPython(importar_escolas, migrations.RunPython.noop),
    ]
