# Generated by Django 6.0.7 on 2026-07-16 14:20

import core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_existing_profiles(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Pessoa = apps.get_model("core", "Pessoa")
    Pessoa.objects.bulk_create(
        [Pessoa(usuario_id=user_id) for user_id in User.objects.values_list("pk", flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, validators=[core.validators.validate_birth_date], verbose_name='data de nascimento')),
                ('genero', models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('NB', 'Não binário'), ('O', 'Outro'), ('NI', 'Prefiro não informar')], max_length=2, verbose_name='gênero')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9()\\s.-]{8,20}$', 'Informe um telefone válido.')], verbose_name='telefone')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('UNIAO_ESTAVEL', 'União estável'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('OUTRO', 'Outro')], max_length=20, verbose_name='estado civil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ('usuario__first_name', 'usuario__username'),
            },
        ),
        migrations.RunPython(create_existing_profiles, migrations.RunPython.noop),
    ]
