# Generated by Django 6.0.7 on 2026-07-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id_escola', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID da escola')),
                ('nome', models.CharField(db_index=True, max_length=255, verbose_name='nome')),
                ('id_municipio', models.BigIntegerField(db_index=True, verbose_name='ID do município')),
                ('sigla_uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('restricao_atendimento', models.CharField(blank=True, max_length=100, verbose_name='restrição de atendimento')),
                ('localizacao', models.CharField(blank=True, max_length=50, verbose_name='localização')),
                ('localidade_diferenciada', models.CharField(blank=True, max_length=100, verbose_name='localidade diferenciada')),
                ('categoria_administrativa', models.CharField(blank=True, max_length=50, verbose_name='categoria administrativa')),
                ('endereco', models.TextField(blank=True, verbose_name='endereço')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='telefone')),
                ('dependencia_administrativa', models.CharField(blank=True, max_length=50, verbose_name='dependência administrativa')),
                ('categoria_privada', models.CharField(blank=True, max_length=100, verbose_name='categoria privada')),
                ('porte', models.CharField(blank=True, max_length=50, verbose_name='porte')),
                ('etapas_modalidades_oferecidas', models.TextField(blank=True, verbose_name='etapas e modalidades oferecidas')),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
                'ordering': ('nome',),
                'indexes': [models.Index(fields=['sigla_uf', 'id_municipio'], name='escola_uf_municipio_idx')],
            },
        ),
    ]
