# Generated by Django 6.0.7 on 2026-07-16 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_normalize_escola_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estado', models.CharField(max_length=100, unique=True, verbose_name='nome do estado')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='sigla')),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'ordering': ('nome_estado',),
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=150, verbose_name='nome da cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='core.estado', verbose_name='estado')),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
                'ordering': ('nome_cidade',),
                'indexes': [models.Index(fields=['estado', 'nome_cidade'], name='cidade_estado_nome_idx')],
                'constraints': [models.UniqueConstraint(fields=('estado', 'nome_cidade'), name='cidade_estado_nome_uniq')],
            },
        ),
    ]
