# Generated by Django 6.0.7 on 2026-08-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='educadorescola',
            name='funcao',
            field=models.CharField(blank=True, choices=[('formador_pacto_anos_iniciais', 'Formador(a) do Pacto | Anos Iniciais'), ('formador_pacto_anos_finais', 'Formador(a) do Pacto | Anos Finais'), ('formador_pacto_ensino_medio', 'Formador(a) do Pacto | Ensino Médio'), ('professor_pacto_anos_iniciais', 'Professor(a) do Pacto | Anos Iniciais'), ('professor_pacto_anos_finais', 'Professor(a) do Pacto | Anos Finais'), ('professor_pacto_ensino_medio', 'Professor(a) do Pacto | Ensino Médio'), ('coordenador_pacto_undime', 'Coordenador(a) do Pacto - Undime'), ('coordenador_pacto_consed', 'Coordenador(a) do Pacto - Consed'), ('outro_profissional_educacao_pacto', 'Outro(a) profissional da Educação ligado(a) ao Pacto'), ('profissional_educacao_nao_pacto', 'Profissional da Educação NÃO ligado(a) ao Pacto'), ('estudante_eja_anos_iniciais', 'Estudante da EJA | Anos Iniciais'), ('estudante_eja_anos_finais', 'Estudante da EJA | Anos Finais'), ('estudante_eja_ensino_medio', 'Estudante da EJA | Ensino Médio'), ('publico_geral', 'Público em geral'), ('convidado_estrangeiro', 'Convidado(a) estrangeiro(a)'), ('outro', 'Outro')], default='', max_length=40, verbose_name='função'),
        ),
    ]
