# Generated by Django 6.0.7 on 2026-07-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_populate_estados_cidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidade',
            name='codigo_ibge',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='código IBGE'),
        ),
        migrations.CreateModel(
            name='CadastroEducador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao_caracterizacao_turmas', models.CharField(choices=[('alfabetizacao_eja', 'Alfabetização EJA'), ('anos_iniciais_eja', 'Anos Iniciais EJA'), ('anos_finais_eja', 'Anos Finais EJA'), ('ensino_medio', 'Ensino Médio'), ('educacao_especial', 'Educação Especial'), ('educacao_profissional', 'Educação Profissional')], max_length=30, verbose_name='função e caracterização das turmas da EJA')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastros_educador', to='core.cidade', verbose_name='cidade de atuação')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastros_educador', to='core.escola', verbose_name='escola')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastros_educador', to='core.estado', verbose_name='estado')),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cadastros_educador', to='core.pessoa', verbose_name='pessoa')),
            ],
            options={
                'verbose_name': 'cadastro de educador',
                'verbose_name_plural': 'cadastros de educadores',
                'ordering': ('-criado_em',),
            },
        ),
    ]
