# Generated by Django 6.0.7 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_educadorescola_funcao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("ensino_fundamental", "Ensino Fundamental"),
                            ("ensino_medio", "Ensino Médio"),
                            ("magisterio", "Magistério/Curso Normal"),
                            ("curso_tecnico", "Curso Técnico"),
                            ("tecnologo", "Tecnólogo"),
                            ("graduacao_licenciatura", "Graduação — Licenciatura"),
                            ("graduacao_bacharelado", "Graduação — Bacharelado"),
                            ("especializacao", "Especialização"),
                            ("mestrado", "Mestrado"),
                            ("doutorado", "Doutorado"),
                            ("pos_doutorado", "Pós-doutorado"),
                        ],
                        max_length=30,
                        verbose_name="nível",
                    ),
                ),
                ("nome_curso", models.CharField(max_length=150, verbose_name="curso")),
                ("instituicao", models.CharField(max_length=150, verbose_name="instituição")),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("cursando", "Cursando"),
                            ("concluido", "Concluído"),
                            ("trancado", "Trancado"),
                            ("interrompido", "Interrompido"),
                        ],
                        max_length=20,
                        verbose_name="situação",
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("presencial", "Presencial"),
                            ("semipresencial", "Semipresencial"),
                            ("ead", "Educação a distância"),
                        ],
                        max_length=20,
                        verbose_name="modalidade",
                    ),
                ),
                (
                    "ano_inicio",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="ano de início"),
                ),
                (
                    "ano_conclusao",
                    models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="ano de conclusão"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "educador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formacoes",
                        to="core.educador",
                        verbose_name="educador",
                    ),
                ),
            ],
            options={
                "verbose_name": "formação",
                "verbose_name_plural": "formações",
                "db_table": "core_formacao",
                "ordering": ("-ano_conclusao", "-ano_inicio", "nome_curso"),
            },
        ),
    ]
