# Generated by Django 6.0.7 on 2026-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_codigos_ibge_cidades'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cadastroeducador',
            constraint=models.UniqueConstraint(fields=('id_pessoa',), name='cadastro_educador_pessoa_uniq'),
        ),
    ]
