# Generated by Django 6.0.7 on 2026-09-11 10:02

import core.models.inscricao
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_educador_cursos_certificados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('palestra', 'Palestra'), ('curso', 'Curso')], default='evento', max_length=10, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=180, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('local', models.CharField(max_length=255, verbose_name='local ou link')),
                ('data_inicio', models.DateTimeField(verbose_name='início')),
                ('data_fim', models.DateTimeField(verbose_name='término')),
                ('inscricoes_inicio', models.DateTimeField(blank=True, null=True, verbose_name='início das inscrições')),
                ('inscricoes_fim', models.DateTimeField(verbose_name='fim das inscrições')),
                ('vagas', models.PositiveIntegerField(blank=True, null=True, verbose_name='número de vagas')),
                ('permite_submissao', models.BooleanField(default=False, verbose_name='permite submissão de trabalho')),
                ('submissoes_fim', models.DateTimeField(blank=True, null=True, verbose_name='fim das submissões')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'db_table': 'core_atividade',
                'ordering': ('data_inicio', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscrito_em', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.atividade', verbose_name='atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_atividades', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'db_table': 'core_inscricao',
                'ordering': ('-inscrito_em',),
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='título do trabalho')),
                ('arquivo', models.FileField(upload_to=core.models.inscricao.trabalho_upload_path, validators=[django.core.validators.FileExtensionValidator(('pdf',), 'Envie um arquivo no formato PDF.'), core.models.inscricao.validate_pdf_size], verbose_name='arquivo em PDF')),
                ('submetido_em', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trabalho', to='core.inscricao', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'trabalho',
                'verbose_name_plural': 'trabalhos',
                'db_table': 'core_trabalho',
                'ordering': ('-submetido_em',),
            },
        ),
        migrations.CreateModel(
            name='Coautor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coautores', to='core.trabalho', verbose_name='trabalho')),
            ],
            options={
                'verbose_name': 'coautor',
                'verbose_name_plural': 'coautores',
                'db_table': 'core_coautor',
                'ordering': ('nome',),
            },
        ),
        migrations.AddConstraint(
            model_name='inscricao',
            constraint=models.UniqueConstraint(fields=('atividade', 'usuario'), name='unique_usuario_atividade'),
        ),
    ]
