# Generated by Django 6.0.7 on 2026-09-11 10:43

from django.db import migrations, models


def separar_links_existentes(apps, schema_editor):
    Atividade = apps.get_model('core', 'Atividade')
    for atividade in Atividade.objects.filter(link='').iterator():
        valor = atividade.local.strip()
        if valor.lower().startswith(('http://', 'https://')):
            atividade.link = valor
            atividade.local = ''
            atividade.save(update_fields=['local', 'link'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_atividade_inscricao_trabalho_coautor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='link do evento on-line'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='local',
            field=models.CharField(blank=True, max_length=255, verbose_name='local/endereço'),
        ),
        migrations.RunPython(separar_links_existentes, migrations.RunPython.noop),
    ]
