# Generated by Django 6.0.7 on 2026-09-11 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_atividade_link_alter_atividade_local'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coautor',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coautorias', to=settings.AUTH_USER_MODEL, verbose_name='usuário cadastrado'),
        ),
    ]
