# Generated by Django 6.0.7 on 2026-09-11

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_coautor_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChamadaAvaliadores",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=180, verbose_name="título da chamada")),
                ("descricao", models.TextField(verbose_name="apresentação da chamada")),
                ("requisitos", models.TextField(verbose_name="requisitos para avaliação")),
                ("inscricoes_inicio", models.DateTimeField(verbose_name="início das candidaturas")),
                ("inscricoes_fim", models.DateTimeField(verbose_name="fim das candidaturas")),
                ("avaliacoes_fim", models.DateTimeField(verbose_name="prazo final das avaliações")),
                ("ativa", models.BooleanField(default=True, verbose_name="chamada publicada")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("atividade", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="chamada_avaliadores", to="core.atividade", verbose_name="atividade")),
            ],
            options={"verbose_name": "chamada de avaliadores", "verbose_name_plural": "chamadas de avaliadores", "db_table": "core_chamada_avaliadores", "ordering": ("inscricoes_inicio", "titulo")},
        ),
        migrations.CreateModel(
            name="CandidaturaAvaliador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("area_atuacao", models.CharField(max_length=180, verbose_name="área de atuação")),
                ("experiencia", models.TextField(verbose_name="experiência acadêmica ou profissional")),
                ("temas_interesse", models.TextField(verbose_name="temas de interesse")),
                ("conflitos_de_interesse", models.TextField(blank=True, help_text="Informe pessoas, instituições ou projetos que você não deve avaliar.", verbose_name="possíveis conflitos de interesse")),
                ("status", models.CharField(choices=[("pendente", "Pendente"), ("aprovada", "Aprovada"), ("rejeitada", "Não aprovada")], default="pendente", max_length=12, verbose_name="status")),
                ("justificativa_decisao", models.TextField(blank=True, verbose_name="observação da coordenação")),
                ("analisada_em", models.DateTimeField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                ("analisada_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="candidaturas_avaliadas", to=settings.AUTH_USER_MODEL, verbose_name="analisada por")),
                ("chamada", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidaturas", to="core.chamadaavaliadores", verbose_name="chamada")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidaturas_avaliador", to=settings.AUTH_USER_MODEL, verbose_name="candidato")),
            ],
            options={"verbose_name": "candidatura de avaliador", "verbose_name_plural": "candidaturas de avaliadores", "db_table": "core_candidatura_avaliador", "ordering": ("-criada_em",)},
        ),
        migrations.CreateModel(
            name="DesignacaoAvaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prazo", models.DateTimeField(blank=True, null=True, verbose_name="prazo")),
                ("liberada_em", models.DateTimeField(auto_now_add=True)),
                ("avaliador", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="designacoes_avaliacao", to=settings.AUTH_USER_MODEL, verbose_name="avaliador")),
                ("liberada_por", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="designacoes_liberadas", to=settings.AUTH_USER_MODEL, verbose_name="liberada por")),
                ("trabalho", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="designacoes_avaliacao", to="core.trabalho", verbose_name="trabalho")),
            ],
            options={"verbose_name": "designação de avaliação", "verbose_name_plural": "designações de avaliação", "db_table": "core_designacao_avaliacao", "ordering": ("prazo", "trabalho__titulo")},
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nota_relevancia", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="relevância")),
                ("nota_metodologia", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="metodologia")),
                ("nota_clareza", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="clareza")),
                ("nota_contribuicao", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="contribuição para a EJA")),
                ("parecer", models.TextField(blank=True, verbose_name="parecer para a coordenação")),
                ("observacoes_autor", models.TextField(blank=True, verbose_name="orientações para os autores")),
                ("recomendacao", models.CharField(blank=True, choices=[("aceitar", "Aceitar"), ("ajustes", "Aceitar com ajustes"), ("rejeitar", "Não aceitar")], max_length=12, verbose_name="recomendação")),
                ("status", models.CharField(choices=[("rascunho", "Rascunho"), ("concluida", "Concluída")], default="rascunho", max_length=10, verbose_name="status")),
                ("atualizada_em", models.DateTimeField(auto_now=True)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("designacao", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="avaliacao", to="core.designacaoavaliacao", verbose_name="designação")),
            ],
            options={"verbose_name": "avaliação", "verbose_name_plural": "avaliações", "db_table": "core_avaliacao"},
        ),
        migrations.AddConstraint(model_name="candidaturaavaliador", constraint=models.UniqueConstraint(fields=("chamada", "usuario"), name="unique_candidatura_usuario_chamada")),
        migrations.AddConstraint(model_name="designacaoavaliacao", constraint=models.UniqueConstraint(fields=("trabalho", "avaliador"), name="unique_trabalho_avaliador")),
    ]
