# Generated by Django 6.0.7 on 2026-09-14 00:09

import core.models.trabalho
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rascunhoinscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='modelo_submissao',
            field=models.CharField(choices=[('academico', 'Trabalho acadêmico'), ('relato', 'Relato de experiência')], default='academico', help_text='O trabalho acadêmico solicita eixo, resumo e palavras-chave. O relato de experiência solicita a caracterização e a proposta detalhada.', max_length=12, verbose_name='modelo para cadastro do trabalho'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='aceitou_originalidade',
            field=models.BooleanField(default=False, verbose_name='declaro que o trabalho é original e de minha responsabilidade'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='aceitou_termo_cessao',
            field=models.BooleanField(default=False, verbose_name='li e aceito o Termo de Cessão de Direitos Autorais'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='aceitou_termo_imagem',
            field=models.BooleanField(default=False, verbose_name='li e aceito o Termo de Uso de Imagem'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='aceitou_termo_relato',
            field=models.BooleanField(default=False, verbose_name='li e aceito o Termo de Uso e Publicação do Trabalho'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='apresentacao',
            field=models.TextField(blank=True, verbose_name='apresentação e justificativa dos conteúdos abordados'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='autorizacao_imagens',
            field=models.CharField(blank=True, choices=[('com', 'Autorizo publicação com uso das imagens'), ('sem', 'Autorizo publicação sem o uso das imagens')], max_length=3, verbose_name='uso de imagens na publicação'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='carga_horaria',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='carga horária'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='consideracoes',
            field=models.TextField(blank=True, verbose_name='considerações e avaliação do processo'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='deseja_participar_publicacao',
            field=models.BooleanField(default=False, verbose_name='tenho interesse em participar da publicação'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='desenvolvimento_metodologico',
            field=models.TextField(blank=True, verbose_name='desenvolvimento metodológico'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='eixo_tematico',
            field=models.CharField(blank=True, max_length=200, verbose_name='eixo temático'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos', to='core.estado', verbose_name='estado da experiência'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='n_participantes',
            field=models.PositiveIntegerField(default=0, verbose_name='total de participantes'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='objetivo_geral',
            field=models.TextField(blank=True, verbose_name='objetivo geral'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='objetivos_especificos',
            field=models.TextField(blank=True, verbose_name='objetivos específicos'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='palavras_chave',
            field=models.CharField(blank=True, help_text='Separe de três a cinco palavras-chave por ponto e vírgula.', max_length=300, verbose_name='palavras-chave'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='periodo_fim',
            field=models.DateField(blank=True, null=True, verbose_name='fim da realização'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='início da realização'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='referencias',
            field=models.TextField(blank=True, verbose_name='referências'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='resumo',
            field=models.TextField(blank=True, verbose_name='resumo'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='termos_aceitos_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='turnos',
            field=models.JSONField(blank=True, default=list, verbose_name='turnos'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='versao_termos',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='EvidenciaTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=core.models.trabalho.evidencia_upload_path, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png'), 'Envie uma imagem JPG ou PNG.'), core.models.trabalho.validate_evidencia_size], verbose_name='imagem')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.trabalho', verbose_name='trabalho')),
            ],
            options={
                'verbose_name': 'evidência do trabalho',
                'verbose_name_plural': 'evidências do trabalho',
                'db_table': 'core_evidencia_trabalho',
                'ordering': ('enviado_em',),
            },
        ),
        migrations.CreateModel(
            name='TrabalhoMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='participantes')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabalhos', to='core.cidade', verbose_name='município')),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.trabalho', verbose_name='trabalho')),
            ],
            options={
                'verbose_name': 'município do trabalho',
                'verbose_name_plural': 'municípios do trabalho',
                'db_table': 'core_trabalho_municipio',
                'ordering': ('cidade__nome_cidade',),
                'constraints': [models.UniqueConstraint(fields=('trabalho', 'cidade'), name='unique_municipio_por_trabalho')],
            },
        ),
    ]
