# Generated by Django 6.0.7 on 2026-09-16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_atividade_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastroPendente",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cpf", models.CharField(db_index=True, max_length=11, verbose_name="CPF")),
                ("email", models.EmailField(db_index=True, max_length=254, verbose_name="e-mail")),
                ("dados", models.JSONField(verbose_name="dados do cadastro")),
                ("criado_em", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "cadastro pendente",
                "verbose_name_plural": "cadastros pendentes",
                "db_table": "core_cadastro_pendente",
            },
        ),
    ]
