# Generated by Django 6.0.7 on 2026-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_tematicasala_mediador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='link',
            field=models.URLField(blank=True, max_length=500, verbose_name='link do evento on-line'),
        ),
    ]
