# Generated by Django 6.0.7 on 2026-10-07 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_atividade_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioCadastroEducador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operacao', models.CharField(choices=[('cadastro', 'Cadastro inicial'), ('edicao', 'Edição')], max_length=10, verbose_name='operação')),
                ('concluido_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='concluído em')),
                ('total_atuacoes', models.PositiveIntegerField(verbose_name='total de atuações após o envio')),
                ('educador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cadastro', to='core.educador', verbose_name='educador')),
            ],
            options={
                'verbose_name': 'envio do cadastro de educador',
                'verbose_name_plural': 'envios do cadastro de educadores',
                'db_table': 'core_envio_cadastro_educador',
                'ordering': ('-concluido_em',),
            },
        ),
    ]
