# Generated by Django 6.0.7 on 2026-10-07 18:05

import django.utils.timezone
from django.db import migrations, models


def importar_registros_legados(apps, schema_editor):
    Educador = apps.get_model("core", "Educador")
    Envio = apps.get_model("core", "EnvioCadastroEducador")
    banco = schema_editor.connection.alias
    cadastros = (
        Educador.objects.using(banco)
        .filter(funcoes__isnull=False, envios_cadastro__isnull=True)
        .annotate(
            primeira_atuacao=models.Min("funcoes__educador_escola__criado_em"),
            total_atuacoes=models.Count("funcoes", distinct=True),
        )
        .order_by("pk")
        .values("pk", "primeira_atuacao", "total_atuacoes")
    )
    registros = [
        Envio(
            educador_id=cadastro["pk"],
            operacao="legado",
            concluido_em=None,
            data_referencia=cadastro["primeira_atuacao"],
            total_atuacoes=cadastro["total_atuacoes"],
        )
        for cadastro in cadastros
    ]
    Envio.objects.using(banco).bulk_create(registros, batch_size=500)


def remover_registros_legados(apps, schema_editor):
    Envio = apps.get_model("core", "EnvioCadastroEducador")
    Envio.objects.using(schema_editor.connection.alias).filter(operacao="legado").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_envio_cadastro_educador'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviocadastroeducador',
            name='data_referencia',
            field=models.DateTimeField(blank=True, help_text='Data de criação da primeira atuação; não comprova a data nem a quantidade de envios antigos.', null=True, verbose_name='primeira atuação do cadastro antigo'),
        ),
        migrations.AlterField(
            model_name='enviocadastroeducador',
            name='concluido_em',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, help_text='Preenchido somente para envios registrados pelo formulário.', null=True, verbose_name='envio concluído em'),
        ),
        migrations.AlterField(
            model_name='enviocadastroeducador',
            name='operacao',
            field=models.CharField(choices=[('cadastro', 'Cadastro inicial'), ('edicao', 'Edição'), ('legado', 'Registro legado')], max_length=10, verbose_name='operação'),
        ),
        migrations.AlterField(
            model_name='enviocadastroeducador',
            name='total_atuacoes',
            field=models.PositiveIntegerField(verbose_name='total de atuações registradas'),
        ),
        migrations.AddConstraint(
            model_name='enviocadastroeducador',
            constraint=models.UniqueConstraint(condition=models.Q(('operacao', 'legado')), fields=('educador',), name='unique_legado_cadastro_educador'),
        ),
        migrations.AddConstraint(
            model_name='enviocadastroeducador',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('concluido_em__isnull', True), ('data_referencia__isnull', False), ('operacao', 'legado')), models.Q(('concluido_em__isnull', False), ('data_referencia__isnull', True), ('operacao__in', ('cadastro', 'edicao'))), _connector='OR'), name='envio_cadastro_datas_por_operacao'),
        ),
        migrations.RunPython(importar_registros_legados, remover_registros_legados),
    ]
