# Generated by Django 6.0.7 on 2026-10-07 18:28

import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_registros_legados_cadastro'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SEQUENCE core_envio_cadastro_numero_seq AS bigint START WITH 1",
            reverse_sql="DROP SEQUENCE core_envio_cadastro_numero_seq",
        ),
        migrations.AddField(
            model_name='enviocadastroeducador',
            name='numero',
            field=models.PositiveBigIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('core_envio_cadastro_numero_seq')", ()), editable=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enviocadastroeducador',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.RunSQL(
            sql="ALTER SEQUENCE core_envio_cadastro_numero_seq OWNED BY core_envio_cadastro_educador.numero",
            reverse_sql="ALTER SEQUENCE core_envio_cadastro_numero_seq OWNED BY NONE",
        ),
    ]
