# Generated by Django 6.0.7 on 2026-10-09 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_numero_envio_cadastro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaosala',
            name='responsavel',
            field=models.ForeignKey(blank=True, help_text='Usuário autorizado a abrir chamadas e registrar presença nesta sala e turno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programacoes_frequencia', to=settings.AUTH_USER_MODEL, verbose_name='responsável pela frequência'),
        ),
        migrations.CreateModel(
            name='ChamadaFrequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberta_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField()),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=16)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.atividade')),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.programacaosala')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('metodo', models.CharField(choices=[('qr', 'QR Code presencial'), ('manual', 'Chamada presencial manual'), ('online', 'Código on-line')], max_length=10)),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.chamadafrequencia')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frequencias', to='core.inscricao')),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frequencias', to='core.programacaosala')),
                ('registrada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'frequência',
                'verbose_name_plural': 'frequências',
                'constraints': [models.UniqueConstraint(fields=('inscricao', 'programacao'), name='frequencia_unica_inscricao_programacao')],
            },
        ),
    ]
